### ISSUE TITLE
configure error: docs not built

### ISSUE THREAD

**Issue by rbgarga** [firehol/iprange#23]
I'm trying to update iprange on FreeBSD ports tree from 1.0.3 to 1.0.4 and I'm getting this error on configure. Looks like the `iprange.1` file is missing but I couldn't find any reference about how to create it or where to get it from.

```
garga@x230 ~/f/p/h/n/i/w/iprange-1.0.4 ❯❯❯ sh autogen.sh
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: not using Libtool
autoreconf-2.69: running: /usr/local/bin/autoconf-2.69 --force
autoreconf-2.69: running: /usr/local/bin/autoheader-2.69 --force
autoreconf-2.69: running: automake --add-missing --copy --force-missing
configure.ac:47: installing './compile'
configure.ac:46: installing './config.guess'
configure.ac:46: installing './config.sub'
configure.ac:45: installing './install-sh'
configure.ac:45: installing './missing'
Makefile.am: installing './depcomp'
autoreconf-2.69: Leaving directory `.'
garga@x230 ~/f/p/h/n/i/w/iprange-1.0.4 ❯❯❯ ./configure
checking whether to enable maintainer-specific portions of Makefiles... no
configure: error: docs not built, use '--disable-man' or --enable-maintainer-mode
```

I'm using a tarball obtained from https://github.com/firehol/iprange/releases

**Comment by philwhineray** [comment]
Where do the sources come from?

If you get the source package it will have the `iprange.1` pre-built in it: https://github.com/firehol/iprange/releases/download/v1.0.4/iprange-1.0.4.tar.gz

If you get the tar direct from the git tag via github, it does not, it only has the manpage source which requires its own build step: https://github.com/firehol/iprange/archive/v1.0.4.tar.gz

If you get the latter you have exactly the choices indicated by configure - either choose to not have docs with `--disable-man` or enable maintainer mode with `--enable-maintainer-mode` so they get built. If you choose the latter, there are extra dependencies that must be met, though (to build the docs), which is why there is a package with them pre-included.

**Comment by rbgarga** [comment]
That worked. Thank you!
